name    'motd'
version '1.0'
source 'git://git.sandsli.dnb.no/...FIXME:'
author 'et2441'
summary 'FIXME:'
description 'FIXME:'
project_page 'http://git.sandsli.dnb.no/...FIXME:'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
